In [2]:
import numpy as n

In [43]:
arr=n.arange(6) #1
print(arr)

[0 1 2 3 4 5]


In [110]:
print("dimention:", arr.ndim)    #2
print("type:",arr.dtype)
print("size:",arr.size)
print("itemsize:",arr.itemsize)
print("shape:",arr.shape)
%time

dimention: 1
type: int32
size: 10
itemsize: 4
shape: (10,)
Wall time: 0 ns


In [6]:
arr3=n.arange(2,7) #3
arr3

array([2, 3, 4, 5, 6])

In [16]:
np.full((4,4),1,dtype=bool) #4

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [48]:
x= n.ones((3,3),dtype=bool) #5
x

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [52]:
 arr3.T   #6

array([2, 3, 4, 5, 6])

In [11]:
type(x)   #7

numpy.ndarray

In [31]:
arr = arr.reshape(3,-1) #8
arr

array([[0, 1],
       [2, 3],
       [4, 5]])

In [24]:
arr1 = n.repeat(5,6).reshape(3,-1) #9
arr1

array([[5, 5],
       [5, 5],
       [5, 5]])

In [58]:
x = n.arange(1,9).reshape(2,2,2) #10
print(x)
print("x[1,0,1]=", x[1,0,1])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
x[1,0,1]= 6


In [69]:
X=x.ravel() #returns straight array     #11
print(X)
print(X.shape)

[1 2 3 4 5 6 7 8]
(8,)


In [78]:
arr=n.arange(10)       #12
n.hsplit(arr,(3,4))

[array([0, 1, 2]), array([3]), array([4, 5, 6, 7, 8, 9])]

In [18]:
n.full_like(x,1)  #13

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [24]:
n.full(x.shape,n.nan)  #14

array([[[nan, nan],
        [nan, nan]],

       [[nan, nan],
        [nan, nan]]])

In [30]:
n.concatenate([arr1,arr],axis=0) #15

array([[5, 5],
       [5, 5],
       [5, 5],
       [0, 1],
       [2, 3],
       [4, 5]])

In [32]:
n.r_[arr,arr1] #16

array([[0, 1],
       [2, 3],
       [4, 5],
       [5, 5],
       [5, 5],
       [5, 5]])

In [33]:
n.stack([arr,arr1]) #17

array([[[0, 1],
        [2, 3],
        [4, 5]],

       [[5, 5],
        [5, 5],
        [5, 5]]])

In [34]:
n.vstack([arr,arr1]) #18

array([[0, 1],
       [2, 3],
       [4, 5],
       [5, 5],
       [5, 5],
       [5, 5]])

In [35]:
n.concatenate([arr1,arr],axis=1) #19

array([[5, 5, 0, 1],
       [5, 5, 2, 3],
       [5, 5, 4, 5]])

In [36]:
n.hstack([arr,arr1]) #20

array([[0, 1, 5, 5],
       [2, 3, 5, 5],
       [4, 5, 5, 5]])

In [39]:
 n.c_[arr,arr1] #21

array([[0, 1, 5, 5],
       [2, 3, 5, 5],
       [4, 5, 5, 5]])

In [53]:
a = np.array([1,2,3])               #22
n.r_[n.tile(a, 3),n.repeat(a, 3)]

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 1, 1, 2, 2, 2, 3, 3, 3])

In [71]:
a = n.arange(10)                         #23
b = n.array([7,2,10,2,7,4,9,4,9,8])          
n.where(a<b)

(array([0, 1, 2, 4, 6, 8], dtype=int64),)

In [61]:
n.intersect1d(a,arr)   #24

array([1, 2, 3])

In [73]:
a[(a>3)&(a<9)]       #25

array([4, 5, 6, 7, 8])

In [74]:
def minn(a,b):             #26
    if(a<b):
        return a
    else:
        return b
minn_n = n.vectorize(minn,otypes=[float])
minn_n(a,b)
    


array([0., 1., 2., 2., 4., 4., 6., 4., 8., 8.])

In [80]:
arr = np.arange(9).reshape(3,-1) #27
arr[:,[2,0,1]]

array([[2, 0, 1],
       [5, 3, 4],
       [8, 6, 7]])

In [81]:
arr[[2,1,0],:] #28

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [82]:
arr[:,::-1] #29

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [87]:
rand = n.random.randint(low=5, high=10, size=(5,3)) #30
rand

array([[5, 9, 9],
       [8, 9, 7],
       [7, 9, 6],
       [8, 5, 5],
       [6, 5, 8]])

In [88]:
n.random.random((5,3))   #31

array([[0.21590096, 0.03630347, 0.05090963],
       [0.51327684, 0.0431491 , 0.68983332],
       [0.45086994, 0.83703785, 0.53075974],
       [0.63794787, 0.8153204 , 0.32101577],
       [0.94403993, 0.19672946, 0.51569768]])

In [90]:
np.random.uniform(5,10, size=(5,3)) #32

array([[6.97819723, 5.06867213, 9.3453443 ],
       [8.88492044, 5.44856547, 6.4786762 ],
       [5.36729978, 7.50915934, 7.81383023],
       [5.23557443, 8.96152151, 5.68702036],
       [9.26799969, 7.18311445, 7.07187047]])

In [127]:
n.set_printoptions(precision=3) #33
rand_arr

array([[9.442, 7.675, 7.394],
       [6.021, 5.087, 7.698],
       [7.942, 5.144, 5.165],
       [9.342, 8.951, 7.82 ],
       [7.994, 9.723, 7.779]])

In [140]:
a=n.random.randint(1,7,size=(3,3))   #34
b=n.random.randint(8,12,size=(3,3))
a@b #matrix product


array([[120, 128, 122],
       [ 36,  39,  35],
       [ 94,  94,  83]])

In [ ]:
a.dot(b) #matrix product   #35

In [147]:
a*b #element wise product   #36

array([[60, 50, 22],
       [ 8, 20,  8],
       [10, 27, 48]])

In [3]:
n.set_printoptions(precision=n.nan)   #37

In [89]:
a = n.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])
c = a.view()
c is a

False

In [82]:
c=a     #38
c is a

True

In [95]:
s = a[ : , 1:3]  #shallow copy #39
s[:]=10
print(a)
print(s)

[[ 0 10 10  3]
 [ 4 10 10  7]
 [ 8 10 10 11]]
[[10 10]
 [10 10]
 [10 10]]


In [96]:
d = a.copy()      #40    
d is a

False

In [97]:
d.base is a     #41               


False

In [111]:
a = n.arange(12).reshape(3,4)   #42
print(a)
i = n.array([[0, 1],                     # indices for the first dim of a
             [1, 2]])
j = n.array([[2, 1],                     # indices for the second dim
              [3, 3]])

c=a[i, j]                                   # i and j must have equal shape
c

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 2,  5],
       [ 7, 11]])

In [106]:
a = n.arange(12).reshape(3,4)   #43
b = a > 4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [109]:
a[b]  #44

array([ 5,  6,  7,  8,  9, 10, 11])

In [117]:
 c=c.transpose()
c

array([[ 2,  5],
       [ 7, 11]])

In [114]:
a = n.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [118]:
 c.cumsum(axis=1) 

array([[ 2,  7],
       [ 7, 18]], dtype=int32)

In [128]:
 b=5
b += c
b

array([[ 7, 10],
       [12, 16]])

In [142]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'   #49
iris = n.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
iris[:3]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

In [144]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'   #50
sepallength = n.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
mu, med, sd = n.mean(sepallength), n.median(sepallength), n.std(sepallength)
print(mu, med, sd)

5.843333333333334 5.8 0.8253012917851409
